"""init

Revision ID: 024b75a61ea0
Revises: 
Create Date: 2022-06-01 13:56:14.493751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024b75a61ea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('be_DB',
    sa.Column('be_id', sa.Integer(), nullable=False),
    sa.Column('be_code', sa.Integer(), nullable=True),
    sa.Column('be_description', sa.String(), nullable=True),
    sa.Column('be_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('be_id', name=op.f('pk_be_DB')),
    sa.UniqueConstraint('be_code', name=op.f('uq_be_DB_be_code'))
    )
    op.create_table('eo_DB',
    sa.Column('eo_id', sa.Integer(), nullable=False),
    sa.Column('eo_code', sa.String(), nullable=True),
    sa.Column('temp_eo_code', sa.String(), nullable=True),
    sa.Column('eo_description', sa.String(), nullable=True),
    sa.Column('be_code', sa.Integer(), nullable=True),
    sa.Column('teh_mesto', sa.String(), nullable=True),
    sa.Column('gar_no', sa.Integer(), nullable=True),
    sa.Column('head_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['be_code'], ['be_DB.be_code'], name=op.f('fk_eo_DB_be_code_be_DB')),
    sa.PrimaryKeyConstraint('eo_id', name=op.f('pk_eo_DB')),
    sa.UniqueConstraint('eo_code', name=op.f('uq_eo_DB_eo_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_DB')
    op.drop_table('be_DB')
    # ### end Alembic commands ###
