"""field operation status

Revision ID: 647e5eceb988
Revises: 
Create Date: 2022-06-14 08:36:43.685547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647e5eceb988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('operation_status')

    # ### end Alembic commands ###
