"""init

Revision ID: 920a80192d2c
Revises: 
Create Date: 2022-05-31 10:21:55.388320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920a80192d2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EO_DB',
    sa.Column('eo_id', sa.Integer(), nullable=False),
    sa.Column('eo_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('eo_id', name=op.f('pk_EO_DB'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EO_DB')
    # ### end Alembic commands ###
